### ISSUE TITLE
South basement wall infill reinforcement.

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#138]
The vertical reinforcement of the CMU walls doesn't reach the CIP lintels.

![image](https://user-images.githubusercontent.com/12873038/72080319-e0a0bf80-32fc-11ea-89c9-d8455fcbb978.png)

**Comment by theoryshaw** [comment]
On that email with the GC, they indicated they did include the vertical reinforcing at that location. I would assume we just need to work on a detail at the CMU and concrete interface.  Similar to this one...

![image](https://user-images.githubusercontent.com/507113/72390382-322bbe80-36f0-11ea-94c1-114b579d17a7.png)

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/72718682-b5c52f80-3b76-11ea-9f8e-c552a555b123.png)
If the vertical reinforcement has not been extended into the top of the wall (see image) we'll need to find some other way to transfer the loads to the first floor.

![image](https://user-images.githubusercontent.com/12873038/72719116-82cf6b80-3b77-11ea-9cf3-0b2f8fb1fa17.png)

The problem with the steel angle solution is that we don't have the HSS struts which transfer the horizontal loads from the CIP lintel bottom to the precast planks.

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
![south_basement_wall](https://user-images.githubusercontent.com/12873329/74139528-d7ed2300-4bf3-11ea-901d-37de22da5c66.jpg)

The two lateral retaining basement walls in the South façade have been modelled supposing the stem laterally supported at the top and fixed at foundation (it acts as a fixed-pin beam). The earth pressure is applied using the at-rest Ko coefficient and surcharge loads are acting on it. To adopt this structural behavior assumption, the vertical section of the wall must be continuous in order to transfer horizontal loads to the precast slab, so the wall can be considered restrained at the top.

For the way in which it has been built, continuity is broken between the CMU wall and the lintel, since the reinforcement of the blocks has not been extended through the concrete lintel. It forces the CMU structure to work as a cantilevered wall, which is much unfavourable than the working hypothesis for which it has been designed.

The proposed solution is to build a new CMU wall on the side in contact with the ground, whose height extends from the foundation to the precast slab level. The contact with the existing wall and lintel is provided at slab-on-ground and precast-slab levels to ensure the transfer of loads to those elements.

**Comment by anaiortega** [comment]
Hi Ryan,
Find sketched two possible solutions to transfer the loads to the precast planks from the South CMU basement walls. The first one can raise the problem of interference between anchors and the lintel bottom reinforcement, so, if selected, we should probably use a WT profile with a wider wing. We also must size the anchorage once the solution is established.
![south_basement_wall_detail](https://user-images.githubusercontent.com/12873329/74243574-4dceb880-4ce0-11ea-8623-6767de764700.jpg)

**Comment by anaiortega** [comment]
Hi Ryan,
Find sketched two possible solutions to transfer the loads to the precast planks from the South CMU basement walls. The first one can raise the problem of interference between anchors and the lintel bottom reinforcement, so, if selected, we should probably use a WT profile with a wider wing. We also must size the anchorage once the solution is established.
![south_basement_wall_detail](https://user-images.githubusercontent.com/12873329/74245393-3513d200-4ce3-11ea-9e3c-468b57bfd485.jpg)

**Comment by theoryshaw** [comment]
Thanks Anna. Don't forget the CMU is 8" and the concrete wallowings 10" so we have a 2" gap on the inside of the wall

**Comment by theoryshaw** [comment]
A 2 3/8" offset to be exact.

**Comment by anaiortega** [comment]
OK, thanks

**Comment by anaiortega** [comment]
Hi @theoryshaw 
Here's the detail
![south_basement_wall_support_detail](https://user-images.githubusercontent.com/12873329/74350170-9e641580-4db5-11ea-956d-1ee8d9bfe73f.jpg)
![south_basement_wall_plan](https://user-images.githubusercontent.com/12873329/74350177-a0c66f80-4db5-11ea-80f3-4c8a4c8ab413.jpg)

**Comment by theoryshaw** [comment]
I just found out that the top of grade will be 3ft below the courtyard elevation.  If that be the case, can we do away with these struts all together?  Could we just do something like this?...

![2020-02-12 10 17 31](https://user-images.githubusercontent.com/507113/74354562-2e3b9c80-4d81-11ea-9cdf-af169951b5db.jpg)


There was a lot of growning on the site yesterday when I brought up this detail, even though they knew it was coming.

**Comment by anaiortega** [comment]
I'm not very confident about that solution. Even if we can size the structural elements to meet the standards with that ground level, I think it's risky to assume that in the future the filling does not reach the top of the wall. We'll try to imagine another solution without affecting the precast.

**Comment by theoryshaw** [comment]
If we have to put the structs in, so be it, but just wanted to ask the question--the gc would be happy if we could eliminate the structs.

**Comment by anaiortega** [comment]
Hi @theoryshaw,
Sorry, we see no options other than:
- install another resisting wall (CMU, corrugated steel sheet, ...) on the side in contact with the ground. As it should almost reach the courtyard elevation, the solution is not very aesthetic if the ground level is 3 ft below.
- Install the struts as represented in the detail above.

**Comment by theoryshaw** [comment]
@anaiortega sounds good.  Can I send your following sketch to the GC?...


![south_basement_wall_support_detail](https://user-images.githubusercontent.com/12873329/74350170-9e641580-4db5-11ea-956d-1ee8d9bfe73f.jpg)
![south_basement_wall_plan](https://user-images.githubusercontent.com/12873329/74350177-a0c66f80-4db5-11ea-80f3-4c8a4c8ab413.jpg)

**Comment by anaiortega** [comment]
Yes, thank you
Le jeu. 13 févr. 2020 à 19:09, Ryan Schultz <notifications@github.com> a
écrit :
