### ISSUE TITLE
update top of wall details to accommodate lateral loads per conversation with Grant

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#75]
@lcpt to provide updated sketch.

**Comment by theoryshaw** [comment]
@lcpt to provide updated sketch.

**Comment by lcpt** [comment]
![top_of_wall_detail](https://user-images.githubusercontent.com/12873038/67792994-64773980-fa7a-11e9-86dd-c8d73ce00286.jpeg)

There you have the modification for the details 3/S201 and 5/S201 to resist the lateral loads of the precast planks. The modifications are as follows:

- The bars drilled thru the precast planks are 2 inches (ca. 5 cm) longer to assure that the pass behind the longitudinal reinforcement (#4 horizontal bar in the sketch).
- There are two new #4 horizontal bars on the top of the wall. Those bars can resist the diaphragm forces introduced by the planks.
- The vertical hairpins become single bars of smaller diameter (#4→#3) because they don't connect the wall with the topping anymore. Two more #3 horizontal bars on this part of the wall ensure the concrete cracking control here.
- The wood framing walls are supported directly on the reinforced concrete.

**Comment by theoryshaw** [comment]
Thanks Luis,
@chopinregis do you want to take a stab at updating 3/S201 and 5/S201?

**Comment by theoryshaw** [comment]
@lcpt, can we put that top rebar 4" down from the top of the wall?  

As you can see below, we're looking to hold the wall down 3" at the door locations. 
![image](https://user-images.githubusercontent.com/507113/67800086-ae4d2900-fa54-11e9-803e-5042732cc077.png)

![image](https://user-images.githubusercontent.com/507113/67799971-6928f700-fa54-11e9-8770-f04332f58041.png)

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/67866097-b1b1e480-fb28-11e9-822a-727d3e12fdf4.png)
We can do this, can't we?

**Comment by theoryshaw** [comment]
Yes, sounds good.

**Comment by chopinregis** [comment]
> Thanks Luis,
> @chopinregis do you want to take a stab at updating 3/S201 and 5/S201?

<img width="548" alt="Annotation 2019-10-30 145612" src="https://user-images.githubusercontent.com/13260872/67889655-a14c3a80-fb25-11e9-8567-c022c60ed2a2.png">

How do these look?

**Comment by theoryshaw** [comment]
i'll markup in the FD.

**Comment by lcpt** [comment]
Thanks @chopinregis. I've left my comments [here](http://dev.first-draft.xyz/d/20tj2lq4k.
