### ISSUE TITLE
Beams and columns at north end of ramp.

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#76]
![image](https://user-images.githubusercontent.com/507113/67695798-b3867700-f973-11e9-8c06-caf17a0825e5.png)

**Comment by anaiortega** [comment]
![20191106_steel_beams_ramp_01](https://user-images.githubusercontent.com/12873329/68293601-93029f00-008e-11ea-9f9f-c2b9fd2b2260.jpg)
![20191106_steel_beams_ramp_02](https://user-images.githubusercontent.com/12873329/68293615-9bf37080-008e-11ea-8d44-4519d221c2b0.jpg)
![20191106_steel_beams_ramp_03](https://user-images.githubusercontent.com/12873329/68293624-9f86f780-008e-11ea-97f0-ed9331cb0ea7.jpg)

**Comment by theoryshaw** [comment]
Thanks @anaiortega!

@chopinregis can you take a stab at detailing these out?

Start with putting the correct beams in the floor plans, at at the correct elevation.  Just put the beams in the floor plans, no details.

Next, you can model up these details. 

Thx.

**Comment by theoryshaw** [comment]
@chopinregis you don't have to put voids for bolts holes, you can use the following bolt family..
https://github.com/OpeningDesign/BIM_Objects/blob/master/Revit_Objects/06%20-%20Wood,%20Plastics,%20and%20Composites/050523%20-%20W_P_C%20-%20Fastenings%20-%20Lag%20Bolt%20or%20Thru%20Bolt.rfa


![image](https://user-images.githubusercontent.com/507113/68339291-e9c9a200-00a9-11ea-8782-ac97b646abc0.png)
for this base plate you can use:
https://github.com/OpeningDesign/BIM_Objects/blob/master/Revit_Objects/05%20-%20Metals/051200%20-%20Structural%20Steel%20Framing/051200%20-%20Structural%20Steel%20Framing%20-%20Base%20Plate%20-%204%20holes.rfa

![image](https://user-images.githubusercontent.com/507113/68339390-1aa9d700-00aa-11ea-8ae6-eb84c374bb89.png)
For this baseplate you can start a new family, from the (4) bolt family above. 

 
![image](https://user-images.githubusercontent.com/507113/68339752-c6ebbd80-00aa-11ea-975d-053c975f9f6d.png)
for this angle, try to create a family like the previous ones.

**Comment by theoryshaw** [comment]
Remember to try and avoid 'voids' and 'cuts'.. they don't translate in our Freemvd workflow. 

https://github.com/OpeningDesign/FreeMVD_WorkFlow/blob/master/Workflow/Workflow.md

**Comment by theoryshaw** [comment]
@anaiortega 

Per the sketch below, how were you thinking this plate would engage the 8" concrete wall beyond?

![image](https://user-images.githubusercontent.com/507113/68357199-24e3c980-00da-11ea-8875-6178a8ff8d78.png)

**Comment by anaiortega** [comment]
Sorry, do not go on with the modeling.  In this design, there are several geometrical and constructive incompatibilities that we must solve previously.

**Comment by theoryshaw** [comment]
Sounds good.  We'll hold off.

**Comment by theoryshaw** [comment]
Also, fyi, i changed the wall circled (red) below to 12" all the way up to accommodate that 10" wide base plate, if you still think that solution the best.

The other wall, however, circled in blue, is still 8" above. 

Latest drawings submitted to GC: CTR\Transfer\20191107 - to GC -Updated Foundation

![image](https://user-images.githubusercontent.com/507113/68400852-555d4f00-013e-11ea-8fac-930b79e60af7.png)

**Comment by anaiortega** [comment]
Thickening the wall doesn't fix the problem, because, even if we'd place the hollow core over the steel beams, we still need some wall highness over the beam to allow room for the plate and upper anchors. We propose two possible solutions: the first one (option 1 in the sketch), by extending the steel beam over the RC wall; the 2nd (option 2) would be an RC solution, cantilevering a  concrete slab instead of the hollow-core.
![North_cantilever](https://user-images.githubusercontent.com/12873329/68469598-c2461700-021a-11ea-8151-eccfe3a95855.png)

**Comment by theoryshaw** [comment]
Hi @anaiortega, could we do something like this?...
https://www.dropbox.com/s/q86os7e90j3yrsp/JQZYiraqAX.mp4?dl=0

This approach helps with fire separation too.

**Comment by anaiortega** [comment]
All right then, we design the bearing plates and anchors for that solution.

**Comment by anaiortega** [comment]
![beams_bearing](https://user-images.githubusercontent.com/12873329/68678738-cd70ae00-055e-11ea-97d4-19b6549591c6.png)
![section](https://user-images.githubusercontent.com/12873329/68678754-d2356200-055e-11ea-84f6-a4acec2c9fe3.png)
This is the detail for bearing the steel beams on the ramp walls. It replaces the detail depicted in section 2-2 of the sketches sent on 11/06.

**Comment by theoryshaw** [comment]
Hi @anaiortega can we push these off center?  If so, what's the max delta?
Just want to create more 'fire separation' between the garage and the residences. 

![chrome_aAXy8AWSTt](https://user-images.githubusercontent.com/507113/68875615-c06fce00-06c8-11ea-9039-f9d9a0244573.png)

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
I'm not sure if I've understood the question right. In this approach, we have the steel column and the central beam (W14x53) in direct contact with the garage space, and, therefore, some kind of passive fire protection material must be applied. Isn't it possible to use the same coating for the lateral beams?. We have very little margin to push the beams off-center since the walls are 8" thickness and the beam flanges (W14x30) are 6.730" width. Perhaps we could give a try to change these last beams to a "C" profile, but not sure it's well-suited to the problem. Maybe, if it does not pose other constructive difficulties, to replace all the steel structure by a cast-in-place slab should work.

**Comment by theoryshaw** [comment]
Thanks Ana!... we'll just go with what you have drafted.

**Comment by theoryshaw** [comment]
@anaiortega 

For those (2) end beams, can we use  w14x43's instead of w14x30's?

It has a wider flange, and will make welding more accessible, or easier to get at.  Also, provides a wider bearing. 

![image](https://user-images.githubusercontent.com/507113/69161769-44eb9380-0ab1-11ea-85cf-99b7fe2812c2.png)
****

**Comment by anaiortega** [comment]
From a resistance standpoint, there is no problem, since the resistant capacity of the W14x43 is bigger than that of the W14x30. The only thing could be the clearance between the top of the hollow core and the top of the beam top flange (13.66-2*0.53*12=0.6""). Usually, the minimum clearance required in order to grout the topping is 3/4", so, in that case, the top of the hollow core should be dapped (the same applies to the central beam W14x53)

**Comment by anaiortega** [comment]
(13.66-2*0.53-12=0.6"") *
