### ISSUE TITLE
Update top of wall details around ramp

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#81]
Hi @lcpt,
With the ramps walls concrete now, can you sketch up some amendments to the following details?

![image](https://user-images.githubusercontent.com/507113/67862317-e786a700-faef-11e9-9cdc-2156366485d5.png)
![image](https://user-images.githubusercontent.com/507113/67862422-169d1880-faf0-11e9-87e4-58752209b04b.png)

**Comment by theoryshaw** [comment]
@lcpt ... also possible get these sketches by tomorrow?

**Comment by lcpt** [comment]
Yes, we'll have it done by tomorrow.

**Comment by lcpt** [comment]
![7_S200_rc_wall_detail](https://user-images.githubusercontent.com/12873038/68025806-0f236e00-fcae-11e9-9c84-62fc766a289c.jpeg)

**Comment by theoryshaw** [comment]
@chopinregis want to take a stab at this detail?  Let's model this detail, per the others.  That is, instead of changing the line work of the existing detail.

**Comment by lcpt** [comment]
![detail_8_s200_replacement](https://user-images.githubusercontent.com/12873038/68055159-4b77be00-fcf0-11e9-881c-d13732f54e2d.jpeg)

**Comment by chopinregis** [comment]
Here is the Update. What would you name the 2x piece that bolts the anchors into the wall?
First draft link here [http://dev.first-draft.xyz/d/20191102_CTR_Structural_Detail/](url)
<img width="957" alt="Annotation 2019-11-03 021723" src="https://user-images.githubusercontent.com/13260872/68081684-24001e80-fde0-11e9-82d2-ce6cd68e01ff.png">

**Comment by lcpt** [comment]
Hi.

Those anchors are simply a piece of threaded steel drilled into the wall concrete and fixed with a resin. You can use a washer and a nut to fix the piece of wood.

On the other hand, I've put the 10" dimension in my sketches for the inverted U-shaped rebar I've placed at the top of the wall (Swiss style of reinforcing :). If you bend the vertical reinforcement  of the wall (which is also fine) you don't need those 10", you can cut the bar at the opposite corner as usual.

**Comment by lcpt** [comment]
Concerning the wood piece under the ladder truss I think it must be thicker (1/2" more) to make sure there is risk of loosing support due to thermal actions.

On the other hand I'll search for the equivalent Titan screws to replace current anchors.
